# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patronymic_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year_of_publication', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patronymic_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('position', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('required_return_date', models.DateField()),
                ('operation_type', models.CharField(choices=[('Выдача', 'Выдача'), ('Приём', 'Приём')], default='Выдача', max_length=2)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.BookCopy')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('library_card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('patronymic_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('passport_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('grop_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='library_card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.Reader'),
        ),
        migrations.AddField(
            model_name='operation',
            name='library_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.LibraryEmployee'),
        ),
        migrations.AddField(
            model_name='author',
            name='book_copy',
            field=models.ManyToManyField(to='Library_App.BookCopy'),
        ),
    ]
